version: "3.9"

services:
  forgottenserver-database:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forgottenserver
    volumes:
      - forgottenserver-database-volume:/var/lib/mysql
      - ./forgottenserver/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
    networks:
      - forgottenserver-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  forgottenserver-phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: forgottenserver-database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - forgottenserver-database
    networks:
      - forgottenserver-network

  forgottenserver-apache:
    build:
      context: apache
      dockerfile: Dockerfile
    volumes:
      - ./apache/ZnoteAAC-1.6:/var/www/html
    ports:
      - 80:80
    depends_on:
      - forgottenserver-database
    networks:
      - forgottenserver-network

networks:
  forgottenserver-network:

volumes:
  forgottenserver-database-volume:
